#!/bin/sh
#
# Copyright 2011 Big Switch Networks
#
# Script to restart OpenFlow related daemons
#
source /etc/find-env

echo "OpenFlow Switch Restart"
sv down ofprotocol
sv down ofswd
echo "Removing existing SDK config files"
rm -f $client_root/config.bcm $client_root/rc.soc
echo "Delaying restart for 5 seconds"
sleep 5

if test "$disable_sysconf" == "yes" ; then 
    echo "disable_sysconf is yes.  Manual configuration required.  Exiting."
    exit 0
fi

sv up ofswd
sv up ofprotocol

touch /tmp/.sys-restart
