#!/usr/local/bin/haserl --shell=lua
Content-type: text/html

<!-- Copyright 2011 Big Switch Networks -->

<% 
   require "web_common"
   require "ui_cs_op"
   require "ui_utils"
   require "ui_config"
%>

<html>
<head>
    <% print(common_includes) %>
	<script type="text/javascript">
	  $(document).ready(function(){
        $('#settings_form').ajaxForm({target: '#settings_content'});
	  });
	</script>
</head>

<body>
<div id="settings_content">

<%
   function chk_var(var)
      if var then print(tostring(var)) else print("not_set") end
   end

   -- TODO Validate text fields properly

   local cfg = { }

   if ENV["REQUEST_METHOD"] == "POST" then
      -- Populate config to save from form settings
      rv, err_str = config_save(FORM)
      if rv < 0 then
         print("<font color=red><b>")
         print("Error saving configuration: " .. err_str .. "</b></font>\n\n")
      else
         print("<font color=green><b>Configuration saved.</b></font><br><br>")
         print("<font color=red>Please <a href=\"/control.html#ui-tabs-2\">reboot the switch</a></font>.")
      end
   end

   -- Refresh the system configuration into the cfg variable
   rv, err_str = config_read(cfg)
   if rv < 0 then
      print("<font color=red><b>")
      print("Error reading configuration: " .. err_str .. "</b></font>\n\n")
   end

%>

<form name="input" action="/cgi-bin/settings" method="POST" id="settings_form">
<table cellspacing="10">
<input type="hidden" name="controller_ip" value=<% chk_var(cfg.controller_ip) %> />
<input type="hidden" name="controller_port" 
       value=<% chk_var(cfg.controller_port) %> />
<input type="hidden" name="datapath_id" value=<% chk_var(cfg.datapath_id) %> />
<input type="hidden" name="log_level" value=<% chk_var(cfg.log_level) %> />
<input type="hidden" name="fail_mode" value=<% chk_var(cfg.fail_mode) %> />
<tr><td>Management interface for this switch:</td>
<td>
<select name="mgmt_if" size="1">
<option name="eth0" <% get_chk_val(cfg.mgmt_if, "eth0", "selected") %> >eth0</option>
<option name="eth1" <% get_chk_val(cfg.mgmt_if, "eth1", "selected") %> >eth1</option>
</select>
</td></tr>
<tr><td>DHCP configuration for this interface:</td>
<td>
<select name="dhcp_config" size="1">
<option value="disable" <% get_chk_val(cfg.dhcp_config, "disable", "selected") %> >disable</option>
<option value="enable" <% get_chk_val(cfg.dhcp_config, "enable", "selected") %> >enable</option>
<option value="vendorext" <% get_chk_val(cfg.dhcp_config, "vendorext", "selected") %> >controller from vendor extension</option>
</select>
</td></tr>
<tr><td>DHCP client identifier for this interface:</td>
<td>
<input type="text" name="dhcp_client_id" value=<% chk_var(cfg.dhcp_client_id) %> />
</td></tr>
<tr><td>IP address for this switch:</td>
<td>
<input type="text" name="ip_addr" value=<% chk_var(cfg.ip_addr) %> />
</td></tr>
<tr><td>Netmask for this IP address:</td>
<td>
<input type="text" name="netmask" value=<% chk_var(cfg.netmask) %> />
</td></tr>
<tr><td>Gateway IP address for this switch:</td>
<td>
<input type="text" name="gateway" value=<% chk_var(cfg.gateway) %> />
</td></tr>
<tr><td>System Name:</td>
<td>
<input type="text" name="system_ref" value=<% chk_var(cfg.system_ref) %> />
</td></tr>
<tr><td>
<input type="submit" value="Save Configuration" /></td>
<td>
</tr>
</table>
</form>

</body>
</html>
